using System.Collections.Concurrent;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using GodMode.Shared.Hubs;
using GodMode.Shared.Models;

// Writes the TypeScript mirror of the hub contract: IProjectHub, IProjectHubClient and every
// GodMode.Shared type they reach, as GodMode.Server's JSON options put them on the wire
// (PascalCase, string enums, nulls left out). The file is only written when its text changes.

if (args is not [var outputPath])
{
    Console.Error.WriteLine("usage: GodMode.TypeGen <output .ts file>");
    return 2;
}

string text;
try
{
    text = TypeScriptWriter.Write(
        hubs: [typeof(IProjectHub), typeof(IProjectHubClient)],
        // Not the hub's: the server list (/servers), and the server to add (services/hostApi.ts addServer)
        extraTypes: [typeof(ServerInfo), typeof(AddServerRequest)]);
}
catch (NotSupportedException ex)
{
    // In MSBuild's error format, so the build lists it as an error rather than an exit code
    Console.Error.WriteLine($"GodMode.TypeGen : error : {ex.Message}");
    return 1;
}

outputPath = Path.GetFullPath(outputPath);
// A checkout may have given the file CRLF line endings (.gitattributes: text=auto); that is no change
if (File.Exists(outputPath) && File.ReadAllText(outputPath).ReplaceLineEndings("\n") == text)
    return 0;

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, text, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"GodMode.TypeGen: wrote {outputPath}");
return 0;

static class TypeScriptWriter
{
    private static readonly NullabilityInfoContext Nullability = new();

    public static string Write(IReadOnlyList<Type> hubs, IReadOnlyList<Type> extraTypes)
    {
        var assembly = hubs[0].Assembly;
        var docs = XmlDocs.Load(assembly);
        var types = CollectTypes(hubs, extraTypes, assembly);

        // A TypeScript type is named by the C# type's name alone, so a nested type, or one in another
        // namespace, could share it; two interfaces of one name would merge into one without a word
        if (types.Concat(hubs).GroupBy(t => t.Name).FirstOrDefault(g => g.Count() > 1) is { } collision)
            throw new NotSupportedException(
                $"{string.Join(" and ", collision.Select(t => t.FullName))} would both be the TypeScript type {collision.Key}; rename one.");

        foreach (var type in types.Where(t => t.IsEnum))
            RequireStringEnum(type);

        var sb = new StringBuilder();
        sb.Append("""
            // <auto-generated>
            // Written by tools/GodMode.TypeGen from GodMode.Shared on every build of GodMode.Server.
            // Do not edit: change the C# contract and rebuild. Hand-written helpers go in ../types.ts.
            // </auto-generated>

            """);

        foreach (var type in types.Where(t => t.IsEnum).OrderBy(t => t.Name, StringComparer.Ordinal))
            WriteEnum(sb, type, docs);

        foreach (var type in types.Where(t => !t.IsEnum).OrderBy(t => t.Name, StringComparer.Ordinal))
            WriteModel(sb, type, docs);

        foreach (var hub in hubs)
            WriteHub(sb, hub, docs, isClient: hub == typeof(IProjectHubClient));

        return sb.ToString().ReplaceLineEndings("\n");
    }

    /// <summary>Every type of <paramref name="assembly"/> the hubs and extra types reach through members.</summary>
    private static IReadOnlySet<Type> CollectTypes(IReadOnlyList<Type> hubs, IReadOnlyList<Type> extraTypes, Assembly assembly)
    {
        var found = new HashSet<Type>();
        var pending = new Stack<Type>(extraTypes.Concat(hubs.SelectMany(HubMethods).SelectMany(m =>
            m.GetParameters().Select(p => p.ParameterType).Append(m.ReturnType))));

        while (pending.TryPop(out var type))
        {
            if (type.HasElementType) { pending.Push(type.GetElementType()!); continue; }
            if (type.IsGenericType) { foreach (var arg in type.GetGenericArguments()) pending.Push(arg); continue; }
            if (type.Assembly != assembly || !found.Add(type) || type.IsEnum) continue;
            foreach (var member in SerializedMembers(type))
                pending.Push(MemberNullability(member).Type);
        }
        return found;
    }

    private static IEnumerable<MethodInfo> HubMethods(Type hub) =>
        hub.GetMethods().OrderBy(m => m.MetadataToken);

    /// <summary>
    /// The members System.Text.Json writes, as the server's options have it (no IncludeFields): public
    /// properties with a public getter, and any property or field opted in with [JsonInclude], less those
    /// [JsonIgnore] always leaves out. Properties come first, as the serializer writes them.
    /// </summary>
    private static IEnumerable<MemberInfo> SerializedMembers(Type type)
    {
        const BindingFlags instance = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;
        var properties = type.GetProperties(instance)
            .Where(p => p.GetIndexParameters().Length == 0 && p.GetMethod is not null
                && (p.GetMethod.IsPublic || p.IsDefined(typeof(JsonIncludeAttribute))))
            .OrderBy(p => p.MetadataToken);
        var fields = type.GetFields(instance)
            .Where(f => f.IsDefined(typeof(JsonIncludeAttribute)))
            .OrderBy(f => f.MetadataToken);
        return properties.Concat<MemberInfo>(fields)
            .Where(m => m.GetCustomAttribute<JsonIgnoreAttribute>() is not { Condition: JsonIgnoreCondition.Always });
    }

    /// <summary>A serialized member's type, and whether it may be null.</summary>
    private static NullabilityInfo MemberNullability(MemberInfo member) => member switch
    {
        PropertyInfo p => Nullability.Create(p),
        FieldInfo f => Nullability.Create(f),
        _ => throw new NotSupportedException($"{member} is neither a property nor a field."),
    };

    /// <summary>
    /// The TypeScript union is of the enum's names, which is what it is on the wire only when the enum
    /// carries its own string converter: the server's options are not the only serializer of it.
    /// </summary>
    private static void RequireStringEnum(Type type)
    {
        if (type.GetCustomAttribute<JsonConverterAttribute>()?.ConverterType != typeof(JsonStringEnumConverter<>).MakeGenericType(type))
            throw new NotSupportedException(
                $"{type.FullName} has no [JsonConverter(typeof(JsonStringEnumConverter<{type.Name}>))], so it may be a number on the wire, not one of its names.");
    }

    /// <summary>A type's name in the XML documentation, where a nested type's is dotted.</summary>
    private static string DocName(Type type) => type.FullName!.Replace('+', '.');

    private static void WriteEnum(StringBuilder sb, Type type, XmlDocs docs)
    {
        sb.Append('\n');
        WriteDoc(sb, docs.Summary($"T:{DocName(type)}"), "");
        var members = type.GetFields(BindingFlags.Public | BindingFlags.Static)
            .Select(f => (Value: f.GetCustomAttribute<JsonStringEnumMemberNameAttribute>()?.Name ?? f.Name,
                          Doc: docs.Summary($"F:{DocName(type)}.{f.Name}")))
            .ToList();

        if (members.All(m => m.Doc is null))
        {
            sb.Append($"export type {type.Name} = {string.Join(" | ", members.Select(m => Quote(m.Value)))};\n");
            return;
        }

        sb.Append($"export type {type.Name} =\n");
        foreach (var (value, doc) in members)
        {
            WriteDoc(sb, doc, "  ");
            sb.Append($"  | {Quote(value)}\n");
        }
        sb.Length--;
        sb.Append(";\n");
    }

    private static void WriteModel(StringBuilder sb, Type type, XmlDocs docs)
    {
        sb.Append('\n');
        WriteDoc(sb, docs.Summary($"T:{DocName(type)}"), "");
        sb.Append($"export interface {type.Name} {{\n");
        foreach (var member in SerializedMembers(type))
        {
            var name = member.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? member.Name;
            var (tsType, nullable) = Map(MemberNullability(member));
            WriteDoc(sb, docs.Summary($"{(member is FieldInfo ? "F" : "P")}:{DocName(type)}.{member.Name}")
                         ?? docs.Param($"T:{DocName(type)}", member.Name), "  ");
            // Nulls are left out of the JSON (JsonIgnoreCondition.WhenWritingNull), so a nullable member may be
            // absent, and so may one its own [JsonIgnore] leaves out at its default (0, false)
            var optional = nullable
                || member.GetCustomAttribute<JsonIgnoreAttribute>() is { Condition: JsonIgnoreCondition.WhenWritingDefault };
            sb.Append($"  {name}{(optional ? "?" : "")}: {(nullable ? Nullable(tsType) : tsType)};\n");
        }
        sb.Append("}\n");
    }

    private static void WriteHub(StringBuilder sb, Type hub, XmlDocs docs, bool isClient)
    {
        sb.Append('\n');
        WriteDoc(sb, docs.Summary($"T:{hub.FullName}"), "");
        sb.Append($"export interface {hub.Name} {{\n");
        var methods = HubMethods(hub).ToList();
        foreach (var method in methods)
        {
            if (methods.Count(m => m.Name == method.Name) > 1)
                throw new NotSupportedException($"{hub.Name}.{method.Name} is overloaded; SignalR invokes by name.");

            var parameters = method.GetParameters().Select(p =>
            {
                var (tsType, nullable) = Map(Nullability.Create(p));
                return $"{p.Name}{(p.HasDefaultValue ? "?" : "")}: {(nullable ? Nullable(tsType) : tsType)}";
            });
            var returns = isClient ? "void" : ReturnType(method);
            WriteDoc(sb, docs.Summary(docs.MethodKey(hub, method.Name)), "  ");
            sb.Append($"  {method.Name}({string.Join(", ", parameters)}): {returns};\n");
        }
        sb.Append("}\n");
    }

    private static string ReturnType(MethodInfo method)
    {
        var info = Nullability.Create(method.ReturnParameter);
        if (!info.Type.IsGenericType) return "Promise<void>";
        var (tsType, nullable) = Map(info.GenericTypeArguments[0]);
        return $"Promise<{(nullable ? Nullable(tsType) : tsType)}>";
    }

    /// <summary>The TypeScript type of a member, and whether it may be null.</summary>
    private static (string Type, bool Nullable) Map(NullabilityInfo info)
    {
        var underlying = System.Nullable.GetUnderlyingType(info.Type);
        var nullable = underlying is not null || info.ReadState == NullabilityState.Nullable;
        var type = underlying ?? info.Type;

        if (type.IsArray)
            return ($"{Element(Map(info.ElementType!))}[]", nullable);

        if (type.IsGenericType)
        {
            var definition = type.GetGenericTypeDefinition();
            var args = info.GenericTypeArguments;
            if (definition == typeof(Dictionary<,>) || definition == typeof(IDictionary<,>)
                || definition == typeof(IReadOnlyDictionary<,>) || definition == typeof(ConcurrentDictionary<,>))
                return ($"Record<{Map(args[0]).Type}, {Value(Map(args[1]))}>", nullable);
            if (definition == typeof(List<>) || definition == typeof(IList<>) || definition == typeof(IReadOnlyList<>)
                || definition == typeof(IEnumerable<>) || definition == typeof(ICollection<>)
                || definition == typeof(IReadOnlyCollection<>))
                return ($"{Element(Map(args[0]))}[]", nullable);
            throw new NotSupportedException($"No TypeScript mapping for {type}.");
        }

        return (Scalar(type), nullable);
    }

    private static string Scalar(Type type) => type switch
    {
        _ when type == typeof(string) || type == typeof(Guid) => "string",
        // ISO 8601 text; a TimeSpan is "hh:mm:ss"
        _ when type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(TimeSpan) => "string",
        _ when type == typeof(bool) => "boolean",
        _ when type == typeof(int) || type == typeof(long) || type == typeof(short) || type == typeof(byte)
            || type == typeof(uint) || type == typeof(ulong) || type == typeof(double) || type == typeof(float)
            || type == typeof(decimal) => "number",
        // Arbitrary JSON, passed through as the client sent or claude wrote it
        _ when type == typeof(JsonElement) || type == typeof(object) => "unknown",
        _ when type.Assembly == typeof(IProjectHub).Assembly => type.Name,
        _ => throw new NotSupportedException($"No TypeScript mapping for {type}."),
    };

    private static string Nullable(string tsType) => tsType == "unknown" ? tsType : $"{tsType} | null";

    private static string Element((string Type, bool Nullable) element) =>
        element.Nullable ? $"({Nullable(element.Type)})" : element.Type;

    private static string Value((string Type, bool Nullable) value) =>
        value.Nullable ? Nullable(value.Type) : value.Type;

    private static string Quote(string value) => $"'{value.Replace("\\", "\\\\").Replace("'", "\\'")}'";

    private static void WriteDoc(StringBuilder sb, string? doc, string indent)
    {
        if (string.IsNullOrWhiteSpace(doc)) return;
        doc = doc.Replace("*/", "*\\/");
        if (!doc.Contains('\n') && indent.Length + doc.Length + 7 <= LineWidth)
        {
            sb.Append($"{indent}/** {doc} */\n");
            return;
        }
        var lines = doc.Split('\n').SelectMany(line => Wrap(line, LineWidth - indent.Length - 3));
        sb.Append($"{indent}/**\n");
        foreach (var line in lines)
            sb.Append(line.Length == 0 ? $"{indent} *\n" : $"{indent} * {line}\n");
        sb.Append($"{indent} */\n");
    }

    private const int LineWidth = 110;

    private static IEnumerable<string> Wrap(string text, int width)
    {
        if (text.Length == 0) { yield return ""; yield break; }
        var line = new StringBuilder();
        foreach (var word in text.Split(' '))
        {
            if (line.Length > 0 && line.Length + 1 + word.Length > width)
            {
                yield return line.ToString();
                line.Clear();
            }
            if (line.Length > 0) line.Append(' ');
            line.Append(word);
        }
        yield return line.ToString();
    }
}

/// <summary>The compiler's XML documentation of an assembly, as plain text for JSDoc.</summary>
sealed class XmlDocs(IReadOnlyDictionary<string, XElement> members)
{
    public static XmlDocs Load(Assembly assembly)
    {
        var path = Path.ChangeExtension(assembly.Location, ".xml");
        if (!File.Exists(path))
            throw new FileNotFoundException($"No XML documentation next to {assembly.Location}; set GenerateDocumentationFile.", path);
        return new(XDocument.Load(path).Descendants("member")
            .ToDictionary(m => (string)m.Attribute("name")!, m => m));
    }

    public string? Summary(string key) =>
        members.TryGetValue(key, out var member) ? Text(member.Element("summary")) : null;

    public string? Param(string key, string name) =>
        members.TryGetValue(key, out var member)
            ? Text(member.Elements("param").FirstOrDefault(p => (string?)p.Attribute("name") == name))
            : null;

    /// <summary>A method's member key; hub methods are not overloaded, so the name identifies it.</summary>
    public string MethodKey(Type type, string name)
    {
        var prefix = $"M:{type.FullName}.{name}";
        return members.Keys.FirstOrDefault(k => k == prefix || k.StartsWith(prefix + "(", StringComparison.Ordinal)) ?? prefix;
    }

    private static string? Text(XElement? element)
    {
        if (element is null) return null;
        var sb = new StringBuilder();
        foreach (var node in element.Nodes())
            sb.Append(node switch
            {
                XText t => t.Value,
                XElement { Name.LocalName: "see" or "seealso" } e =>
                    (string?)e.Attribute("langword") ?? CrefName((string?)e.Attribute("cref")),
                XElement { Name.LocalName: "paramref" or "typeparamref" } e => (string?)e.Attribute("name"),
                XElement { Name.LocalName: "c" } e => $"`{e.Value}`",
                XElement { Name.LocalName: "para" } e => $"\n\n{Text(e)}\n\n",
                XElement e => e.Value,
                _ => "",
            });

        // Paragraph breaks survive; every other run of whitespace is one space
        var paragraphs = Regex.Split(sb.ToString(), @"\n\s*\n")
            .Select(p => Regex.Replace(p, @"\s+", " ").Trim())
            .Where(p => p.Length > 0);
        var text = string.Join("\n\n", paragraphs);
        return text.Length == 0 ? null : text;
    }

    /// <summary><c>T:GodMode.Shared.Models.ProjectStatus.PullRequest</c> reads as <c>ProjectStatus.PullRequest</c>.</summary>
    private static string CrefName(string? cref)
    {
        if (cref is null) return "";
        var name = cref[(cref.IndexOf(':') + 1)..];
        var paren = name.IndexOf('(');
        if (paren >= 0) name = name[..paren];
        var parts = name.Split('.');
        return cref.StartsWith("T:", StringComparison.Ordinal) || parts.Length < 2
            ? parts[^1]
            : $"{parts[^2]}.{parts[^1]}";
    }
}
