<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Octokit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GodMode.Shared\GodMode.Shared.csproj" />
		<ProjectReference Include="..\SignalR.Proxy\SignalR.Proxy.csproj" />
	</ItemGroup>

</Project>
